### ISSUE TITLE
Vehicle Configuration

### ISSUE THREAD

**Issue by gleski** [athal7/homebridge-hyundai-bluelink#10]
**Describe Your Problem:**
I'm trying to enter the correct vehicle information in the web version of HOOBS at hoobs.local. Under the Vehicle field there is this text [ ]. I try to enter my vehicle's VIN in the field using the format [XXXXXXXXXXXXXXXXXXXXX] but every time I hit save the field reverts back to an empty set of brackets (i.e. [ ]) Then nothing shows up in the Home app.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.

I'm not using a config.json, I'm configuring it in the local website
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/11761755/112531226-5152c100-8d75-11eb-8d68-498b5751972b.png)

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by athal7** [comment]
This is an issue with HOOBS, because it does not yet support array fields in the config schema https://github.com/hoobs-org/HOOBS/issues/895. I'm not familiar with HOOBS so I'm not sure if there is a workaround prior to the release where they plan to support this field type. Sorry!
