### ISSUE TITLE
Error Code 502

### ISSUE THREAD

**Issue by fratinize** [athal7/homebridge-hyundai-bluelink#11]
Just Installed this plug in, didn't see any install errors, but when Launched in homebridge, it fails
my credentials are 100% correct as well as my vin and pin, not sure what I am missing thank you for any help or direction. This plug-in is current.

**Logs:**

```
[4/7/2021, 3:48:46 PM] [homebridge-hyundai-bluelink] Restarting Process...
Initializing HAP-NodeJS v0.9.4...
[4/7/2021, 3:48:47 PM] [homebridge-hyundai-bluelink] Launched child bridge with PID 10356
[4/7/2021, 3:48:48 PM] Registering platform 'homebridge-hyundai-bluelink.Hyundai'
[4/7/2021, 3:48:48 PM] [homebridge-hyundai-bluelink] Loaded homebridge-hyundai-bluelink v1.2.13 child bridge successfully
[4/7/2021, 3:48:48 PM] Loaded 0 cached accessories from cachedAccessories.0E1255E4C007.
Preparing Advertiser for 'homebridge-hyundai-bluelink 36E9' using bonjour-hap backend!
Starting to advertise 'homebridge-hyundai-bluelink 36E9' using bonjour-hap backend!
[4/7/2021, 3:48:48 PM] Homebridge v1.3.4 (homebridge-hyundai-bluelink) is running on port 50347.
[4/7/2021, 3:48:49 PM] [homebridge-hyundai-bluelink] Client Error GotError [HTTPError]: Response code 502 (Bad Gateway)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-hyundai-bluelink/node_modules/got/source/as-promise.js:74:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  host: 'api.telematics.hyundaiusa.com',
  hostname: 'api.telematics.hyundaiusa.com',
  method: 'POST',
  path: '/v2/ac/oauth/token',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://api.telematics.hyundaiusa.com/v2/ac/oauth/token',
  gotOptions: {
    path: '/v2/ac/oauth/token',
    protocol: 'https:',
    slashes: true,
    auth: null,
    host: 'api.telematics.hyundaiusa.com',
    port: null,
    hostname: 'api.telematics.hyundaiusa.com',
    hash: null,
    search: null,
    query: null,
    pathname: '/v2/ac/oauth/token',
    href: 'https://api.telematics.hyundaiusa.com/v2/ac/oauth/token',
    retry: {
      retries: [Function (anonymous)],
      methods: [Set],
      statusCodes: [Set],
      errorCodes: [Set]
    },
    headers: {
      'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
      client_secret: 'GXZveJJAVTehh/OtakM3EQ==',
      client_id: '815c046afaa4471aa578827ad546cc76',
      accept: 'application/json',
      'accept-encoding': 'gzip, deflate',
      'content-type': 'application/json',
      'content-length': 68
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: false,
    form: false,
    json: true,
    cache: false,
    useElectronNet: false,
    method: 'POST',
    body: '{"username":"fxxxxx@xxxxxx.com","password”:”xxxxxxxxxxxxxxxxxx”}’
  },
  statusCode: 502,
  statusMessage: 'Bad Gateway',
  headers: {
    date: 'Wed, 07 Apr 2021 19:48:49 GMT',
    server: 'Oracle-Application-Server-11g',
    'access-control-allow-methods': 'POST, GET, PUT,, POST, GET',
    'access-control-max-age': '1000, 3600',
    'access-control-allow-headers': 'language, offset, UCID, From, x-requested-with, Content-Type, origin, authorization, accept, client-security-token, accesstoken, clientId, clientSecret, x-requested-with',
    'access-control-allow-credentials': 'true',
    'content-language': 'en,en-us',
    elapsedtime: '6',
    'x-oracle-dms-ecid': '000JIgmPJgH2vHTpm8T4iZ0004RQ00q6Iv, 000JIgmPJgH2vHTpm8T4iZ0004RQ00q6Iv',
    'access-control-allow-origin': '*',
    guid: 'a95ddf2c373f4a3a84521ab666923183',
    'x-oracle-dms-rid': '0:1, 0:1',
    'access-control-expose-headers': 'transactionId, transactionDate, offset, language',
    connection: 'close',
    'transfer-encoding': 'chunked',
    'content-type': 'application/json',
    'public-key-pins-report-only': 'pin-sha256="NoKLOeGQwqGYqDPaJlMu2LvRPdj298oekgJLhW1wiFA="; pin-sha256="RRM1dGqnDFsCJXBTHky16vi1obOlCgFFn/yOhI/y+ho="; max-age=86400; report-uri="https://hyundaiusa.com/pin/"'
  },
  body: {
    errorSubCode: 'C500',
    errorSubMessage: ' Invalid Request.',
    errorMessage: '"There was an error processing your request. Please try again."',
    errorCode: 502
  }
}
```

**Plugin Config:**

```json
{
    "credentials": {
        "username": "myname@domian.com",
        "password": "my password",
        "region": "US",
        "pin": "1234"
    },
    "vehicles": [
        {
            "vin": "KM3333333333U084444",
            "maxRange": 500
        }
    ],
    "remoteStart": {
        "cool": true,
        "heat": false,
        "defrost": false,
        "temperature": 72,
        "igniOnDuration": 15
    },
    "refreshInterval": 20,
    "_bridge": {
        "username": "0E:12:55:E4:C0:xx",
        "port": 50345
    },
    "platform": "Hyundai"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 1.34
* **Node.js Version**: 14.16.0
* **NPM Version**: 7.8.0
* **Operating System**:

**Comment by athal7** [comment]
I think you might be hitting the API rate limit similar to https://github.com/Hacksore/bluelinky/issues/80

**Comment by fratinize** [comment]
Not Sure if I see Why this could be similar. I do not use the App much at all, let alone locking and unlocking. What else might be going on? TY

**Comment by fratinize** [comment]
I'd Imagine I am Beyond todays limit then, I just upped to 6000. Do I Need to Restart or does it automatically query? Thank You again for your help

**Comment by athal7** [comment]
Gotta restart. Config loads into memory at boot--
Andrew Thal
athal7.com

**Comment by fratinize** [comment]
Same result ☹️

**Comment by athal7** [comment]
I wonder if you have to wait for a new day after resetting so that the rate limit resets?

**Comment by fratinize** [comment]
I will give it a shot on Monday 
Enjoy your weekend

**Comment by fratinize** [comment]
Attempted this again and am getting same result

**Comment by athal7** [comment]
Thanks for trying. Honestly I'm not sure what's going on. This library is just a light wrapper around Bluelinky, so anything related to the Hyundai API would likely need to be solved over there.

**Comment by fratinize** [comment]
Please Excuse the Ignorance, But it seems bluelinky is not a "home bridge" plug in, am I to Understand it Runs on its own but uses my config.json from homebridge? Its ok to Run on the Same Server as Homebridge? A Little Confused

**Comment by athal7** [comment]
Bluelinky is the library that this homebridge plugin uses to communicate
with the Hyundai API. This plugin is just a wrapper around that API client
that speaks homebridge.

**Comment by fratinize** [comment]
Can I install on my pi that’s running homebridge ?

**Comment by athal7** [comment]
Sure
-- 
Andrew Thal
athal7.com

**Comment by fratinize** [comment]
So Go the bluelinky to Work, I can Query and Get data back, I am still seeing this same error on the Homebridge plug. Not Sure What else I am Missing. like I said I am new to this. Is Bluelinky Supposed to be running as a Service?

**Comment by athal7** [comment]
What version of bluelinky? I think we are a few versions behind in the dependency hefe

**Comment by athal7** [comment]
@fratinize try installing from this branch and let me know if it fixes your issue

https://github.com/athal7/homebridge-hyundai-bluelink/pull/12

**Comment by fratinize** [comment]
Homebridge UI Shows me 1.2.13 and is the Latest I will try this very shortly,
Thank you

**Comment by fratinize** [comment]
A bit embarrassed, but How do I install from this branch? I see the 5 changes. is there an installer? sorry confused

**Comment by athal7** [comment]
just published a new release, try updating now

**Comment by fratinize** [comment]
Awesome Worked Right off, I see My Ignition and My Doors. Cool.
Unfortunately, the Doors have no Response, Nor Does the Ignition.
Also I Do not see any Logs in Homebridge, How would I add Debug=yes?
Thank You for your help

**Comment by athal7** [comment]
Fantastic! If you are using the homebridge config ui, there should be an option in the top level homebridge configuration. Or if you are running with the command line you can start the process with DEBUG=1

**Comment by fratinize** [comment]
Thanx turned it on and see some logs will investigate and reach out thanx again

**Comment by fratinize** [comment]
So this morning I see my car is off and doors are locked was able to unlock the doors. Very cool. Thank you for fixing this. Will try starting the car later today. 
Is there a way to add the odometer and gas level?

**Comment by athal7** [comment]
🎉 the gas level should already be available. Can look into whether there’s a homebridge “service type” that would be a good fit for the odometer. Open to thoughts if you care to take a look as well https://developers.homebridge.io/

**Comment by fratinize** [comment]
Thanx for this info it’ll take some time for me to wrap my mind around this coding very new 

Where would I see the gas level?
I see my battery in the ignition and it shows 37%? Car battery should be fine (car is only a month old) and my gas tank is at 3/4 full

**Comment by athal7** [comment]
Battery is the closest service type I could find to gas. So in a car with fuel the "battery" is the gas level. If it's an electric car it represents that capacity.

**Comment by fratinize** [comment]
Where does this number come from? I dont see it in the app and not in bluelinky.
Hk shows 37%
my physical gas gauge shows between 1/2 and 3/4 of a tank I would think 50-65%
Is it possible to show this % on the vehicle tile?

**Comment by athal7** [comment]
https://github.com/athal7/homebridge-hyundai-bluelink/blob/main/src/services/range.ts

**Comment by athal7** [comment]
I don't think the battery percentage service type can show at the top level in the home app, it appears to only be able to be a property of another accessory and show up in status when low.

**Comment by athal7** [comment]
Going to go ahead and close this issue since the original problem was fixed. Feel free to open up something new if you have other bugs/features.

**Comment by fratinize** [comment]
Np
Ty for your help
