### ISSUE TITLE
Status of Door locks dont update

### ISSUE THREAD

**Issue by yonigold1** [athal7/homebridge-hyundai-bluelink#21]
**Describe The Bug:**
Status does of Door locks does not update

**To Reproduce:**
lock the door from either the car or the key fob or the bluelink app 

**Expected behavior:**
i would imagine that if i lock it from the bluelink app or the fob that the door lock in homekit would say locked

**Logs:**
ill attach at a later point 

**Plugin Config:**

```json
        {
            "credentials": {
                "username": "REMOVED",
                "password": "REMOVED",
                "region": "CA",
                "brand": "hyundai",
                "pin": "REMOVED"
            },
            "vehicles": [
                {
                    "vin": "REMOVED"
                }
            ],
            "remoteStart": {
                "cool": true,
                "heat": false,
                "defrost": false,
                "temperature": "0BH",
                "igniOnDuration": 10
            },
            "platform": "Hyundai" 
```

**Environment:**

* **Plugin Version**: v1.3.4
* **Homebridge Version**:  v1.3.5
* **Node.js Version**: v14.17.0
* **NPM Version**: v7.13.0
* **Operating System**:  Homebridge - Raspbian

**Comment by athal7** [comment]
Just added an explanation for this to the readme:

https://github.com/athal7/homebridge-hyundai-bluelink/blob/main/README.md#status-refresh-delay

> Due to Hyundai's [API Rate Limits](https://github.com/Hacksore/bluelinky/wiki/API-Rate-Limits), the car status (locked, on/off, range) is only updated once per hour. Actions taken from homebridge get automatically refreshed, but actions taken elsewhere (e.g. bluelink app, key fab) may not display in homebridge for up to an hour.
