### ISSUE TITLE
Since Recent Updates, Seems Authentication Fails?

### ISSUE THREAD

**Issue by fratinize** [athal7/homebridge-hyundai-bluelink#26]
Doors on my Hyundai continually say "Locking...." 

**Describe Your Problem:**

The Car is physically Locked, the blue link app says its locked, but Home Kit is just Spinning away. I have Removed from home Kit, Reinstalled bridge, rebooted Pi, but continually get error below

**Logs:**
[7/10/2021, 8:54:40 AM] [homebridge-hyundai-bluelink] Client Error $ [ManagedBluelinkyError]: @AmericanController.login: [400] Bad Request on [POST] https://api.telematics.hyundaiusa.com/v2/ac/oauth/token - {"errorSubCode":"C401","errorSubMessage":"An updated version of this app is now available. Please download the latest version.","errorMessage":"An updated version of this app is now available. Please download the latest version.","errorCode":400}
    at _ (/usr/local/lib/node_modules/homebridge-hyundai-bluelink/node_modules/bluelinky/dist/index.js:17:11535)
    at U.<anonymous> (/usr/local/lib/node_modules/homebridge-hyundai-bluelink/node_modules/bluelinky/dist/index.js:17:13933)
    at Generator.throw (<anonymous>)
    at a (/usr/local/lib/node_modules/homebridge-hyundai-bluelink/node_modules/bluelinky/dist/index.js:17:136)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  source: GotError [HTTPError]: Response code 400 (Bad Request)
      at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-hyundai-bluelink/node_modules/got/source/as-promise.js:74:19)
      at processTicksAndRejections (internal/process/task_queues.js:95:5) {
    host: 'api.telematics.hyundaiusa.com',
    hostname: 'api.telematics.hyundaiusa.com',
    method: 'POST',
    path: '/v2/ac/oauth/token',
    socketPath: undefined,
    protocol: 'https:',
    url: 'https://api.telematics.hyundaiusa.com/v2/ac/oauth/token',
    gotOptions: {
      path: '/v2/ac/oauth/token',
      protocol: 'https:',
      slashes: true,
      auth: null,
      host: 'api.telematics.hyundaiusa.com',
      port: null,
      hostname: 'api.telematics.hyundaiusa.com',
      hash: null,
      search: null,
      query: null,
      pathname: '/v2/ac/oauth/token',
      href: 'https://api.telematics.hyundaiusa.com/v2/ac/oauth/token',
      retry: [Object],
      headers: [Object],
      hooks: [Object],
      decompress: true,
      throwHttpErrors: true,
      followRedirect: true,
      stream: false,
      form: false,
      json: true,
      cache: false,
      useElectronNet: false,
      method: 'POST',
      body: '{"username":"f.......@.com","password":"xxxxxxxxxxxxxx"}'
    },
    statusCode: 400,
    statusMessage: 'Bad Request',
    headers: {
      date: 'Sat, 10 Jul 2021 12:54:40 GMT',
      server: 'Oracle-Application-Server-11g',
      'access-control-allow-methods': 'POST, GET, PUT,, POST, GET',
      'access-control-max-age': '1000, 3600',
      'access-control-allow-headers': 'language, offset, UCID, From, x-requested-with, Content-Type, origin, authorization, accept, client-security-token, accesstoken, clientId, clientSecret, x-requested-with',
      'access-control-allow-credentials': 'true',
      'content-language': 'en,en-us',
      elapsedtime: '6',
      'x-oracle-dms-ecid': '000LDJEcGGu2vHTpm8S4yZ0000oP00DR5l, 000LDJEcGGu2vHTpm8S4yZ0000oP00DR5l',
      'access-control-allow-origin': '*',
      guid: '2028655ff99e46e986ded1f78b538c18',
      'x-oracle-dms-rid': '0:1, 0:1',
      'access-control-expose-headers': 'transactionId, transactionDate, offset, language',
      connection: 'close',
      'transfer-encoding': 'chunked',
      'content-type': 'application/json',
      'public-key-pins-report-only': 'pin-sha256="NoKLOeGQwqGYqDPaJlMu2LvRPdj298oekgJLhW1wiFA="; pin-sha256="RRM1dGqnDFsCJXBTHky16vi1obOlCgFFn/yOhI/y+ho="; max-age=86400; report-uri="https://hyundaiusa.com/pin/"'
    },
    body: {
      errorSubCode: 'C401',
      errorSubMessage: 'An updated version of this app is now available. Please download the latest version.',
      errorMessage: 'An updated version of this app is now available. Please download the latest version.',
      errorCode: 400
    }
  }
}
```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**: 
All Current

**Comment by athal7** [comment]
Homebridge config ui lets you install prior versions of plugins now. Maybe worth doing that for now while this gets sorted in the bluelinky dependency

**Comment by fratinize** [comment]
Down grade to previous same error

**Comment by athal7** [comment]
Weird. I'll see if I can reproduce. The log message you received is interesting, mentioning an updated version of the app being available. Not sure what app that's referring to... wonder if it's the Hyundai phone app or something in the car

**Comment by athal7** [comment]
I'm able to reproduce this issue, will surface to bluelinky
