### ISSUE TITLE
No accessories with 1.3.7 and Hoobs 4.0.#

### ISSUE THREAD

**Issue by RayWilliamsII** [athal7/homebridge-hyundai-bluelink#27]
**Describe The Bug:**
Using Hoobs 4 and installing homebridge-hyundai-bluelink into a dedicated bridge, no accessories (vehicles) are loaded.  I do not receive any errors.  This is using a clean install of Hoobs 4 and all of my other plugins are working.  I have tried both versions 1.3.6 and 1.3.7 and the issue persist.

**To Reproduce:**
Install plugin into dedicated bridge using Hoobs 4.0.80.
Use Advanced settings to apply the configuration.
I've tried multiple restarts and reboots.

**Expected behavior:**
My vehicle will be added to the available accessories

**Logs:**

```
7/11/2021, 10:03:32 PMHyundai Bluelink BridgeInitializing HAP-NodeJS v0.9.4...
7/11/2021, 10:03:34 PMHyundai Bluelink BridgeLoaded plugin 'homebridge-hyundai-bluelink'
7/11/2021, 10:03:34 PMHyundai Bluelink BridgeRegistering platform 'homebridge-hyundai-bluelink.Hyundai'
7/11/2021, 10:03:34 PMHyundai Bluelink BridgeLoading 1 platforms...
7/11/2021, 10:03:34 PMHyundai Bluelink BridgeHyundaiExecuted didFinishLaunching callback
7/11/2021, 10:03:34 PMHyundai Bluelink BridgeHyundaiHyundai config: {
  platform: 'Hyundai',
  credentials: {
    password: ‘*******’,
    username: ‘*******’,
    region: 'US',
    brand: 'hyundai',
    pin: ‘####’
  },
  vehicles: [ { vin: ‘*******’, maxRange: 500 } ],
  remoteStart: {
    cool: false,
    heat: false,
    defrost: false,
    temperature: 70,
    igniOnDuration: 15
  }
}
7/11/2021, 10:03:34 PMHyundai Bluelink BridgePreparing Advertiser for 'Hyundai Bluelink Bridge EFCF' using bonjour-hap backend!
7/11/2021, 10:03:34 PMHyundai Bluelink BridgeSetup URI 'X-HM://0023ISYWYGXM0'
7/11/2021, 10:03:34 PMHyundai Bluelink BridgeStarting to advertise 'Hyundai Bluelink Bridge EFCF' using bonjour-hap backend!
7/11/2021, 10:03:34 PMHyundai Bluelink BridgeBridge is running on port 57826.
```

**Plugin Config:**
```
"accessories": [],
"platforms": [
    {
        "platform": "Hyundai",
        "credentials": {
            "password": “*******”,
            "username": “*******”,
            "region": "US",
            "brand": "hyundai",
            "pin": “####”
        },
        "vehicles": [
            {
                "vin": “*******”,
                "maxRange": 500
            }
       ],
        "remoteStart": {
            "cool": false,
            "heat": false,
            "defrost": false,
            "temperature": 70,
            "igniOnDuration": 15
        }
    }
]
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.3.7
* **Homebridge Version**: 1.3.3 (Hoobs 4.0.80)
* **Node.js Version**: 14.16.0
* **NPM Version**: 7.10.0
* **Operating System**: Raspbian GNU/Linux 10 (buster)

**Comment by athal7** [comment]
@RayWilliamsII are you able to turn on debug level logging?

**Comment by athal7** [comment]
i believe this has the same root cause as #26

**Comment by RayWilliamsII** [comment]
@athal7 - I haven’t found a way to enable debugging in the new Hoobs4 model. I’ve tried toggling the debug option from the log view, but it didn’t reveal and additional details that what I provided before. I’ll keep digging. Let me know if you happen to know the steps to enable debug logs properly.

**Comment by athal7** [comment]
I'm fairly confident that this is part of the same upstream issue https://github.com/Hacksore/bluelinky/issues/155, don't worry about the debug logs
