### ISSUE TITLE
AC not turning on after successful remote start

### ISSUE THREAD

**Issue by jcarusone1650** [athal7/homebridge-hyundai-bluelink#29]
**Describe The Bug:**
2021 Palisade - When remote starting the vehicle the AC settings don't seem to turn on.  The push notification from Hyundai app shows car started with HVAC however the car does start just with no AC. If I use Bluelinky directly with the config below everything works correctly.

**Bluelinky Config** (Working)
    const response = await vehicle.start({
        airCtrl: true,
        igniOnDuration: 10,
        airTempvalue: 65
    })

**Homebridge-Hyundai-Bluelink Config** (Not Working)
"remoteStart": {
  "cool": true,
  "heat": false,
  "defrost": false,
  "temperature": 65,
  "igniOnDuration": 10
}

**To Reproduce:**

Use Homekit to start vehicle with the config above

**Expected behavior:**

Vehicle should start with the HVAC set to 65 degrees

**Logs:**

**Plugin Config:**

"remoteStart": {
  "cool": true,
  "heat": false,
  "defrost": false,
  "temperature": 65,
  "igniOnDuration": 10
}

**Screenshots:**

**Environment:**

homebridge-hyundai-bluelink v1.3.9
Raspbian GNU/Linux Buster (10)
v14.17.6
v6.14.15

**Comment by athal7** [comment]
fixed in https://github.com/athal7/homebridge-hyundai-bluelink/releases/tag/1.3.10
